### ISSUE TITLE
Is this still work?, chromium immediately closed

### ISSUE THREAD

**Issue by Satria41** [stepney141/pixiv-token-extractor#1]
Issue: chromium immediately closed after the login page loaded for 1-2 second
On the cmd:
[!]: TypeError: Cannot read property 'type' of undefined
[!]: Error: Failed to obtain a login token. Please try again in the GUI mode.

**Comment by stepney141** [comment]
Thank you for the bug report!
I have just updated some XPath strings because the DOM structure of the page had changed.
Please try again with the latest version.

```
$ node index.js login --gui
[INFO]: Generated code_verifier: ***** // confidential
[INFO]: Launched Chromium browser
https://app-api.pixiv.net/web/v1/login?code_challenge=*****&code_challenge_method=S256&client=pixiv-android
[INFO]: Succeed in logging in pixiv
[+]: Success!
[INFO] Get code: *****  // confidential
access_token: ***** // confidential
refresh_token: ***** // confidential
expires_in: 3600
```

**Comment by Satria41** [comment]
> Thank you for the bug report! I have just updated some XPath strings because the DOM structure of the page had changed. Please try again with the latest version.
> 
> ```
> $ node index.js login --gui
> [INFO]: Generated code_verifier: ***** // confidential
> [INFO]: Launched Chromium browser
> https://app-api.pixiv.net/web/v1/login?code_challenge=*****&code_challenge_method=S256&client=pixiv-android
> [INFO]: Succeed in logging in pixiv
> [+]: Success!
> [INFO] Get code: *****  // confidential
> access_token: ***** // confidential
> refresh_token: ***** // confidential
> expires_in: 3600
> ```

Thanks you 😊, it works with several try
